### ISSUE TITLE
Corrupted archives

### ISSUE THREAD

**Issue by jordangottlieb-ych** [thephpleague/flysystem-azure-blob-storage#10] opened 2018-11-09 00:51 UTC
PHP 7.1, Laravel 5.6.

I'm using these to automate offsite backups:
* https://github.com/spatie/laravel-backup
* https://github.com/thephpleague/flysystem
* https://github.com/thephpleague/flysystem-azure-blob-storage
* https://github.com/spatie/flysystem-dropbox

When I run a backup, the zip archive is generated correctly and stored locally, on Dropbox and in Azure.

* The local zip archive extracts just fine..
* The Dropbox zip archive extracts just fine..
## The Azure zip archive says it's corrupted and will not extract
I use Microsoft Azure Storage Explorer to manually download the archive from blob storage.
![image](https://user-images.githubusercontent.com/33668261/48236259-4babda80-e376-11e8-80ba-5d4b054f8064.png)

Any ideas? Here's my AzureServiceProvider in Laravel if it helps:

```
namespace App\Providers;

use Storage;
use League\Flysystem\Filesystem;
use Illuminate\Support\ServiceProvider;
use MicrosoftAzure\Storage\Blob\BlobRestProxy;
use League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter;

class AzureServiceProvider extends ServiceProvider
```

**Comment by jordangottlieb-ych** [comment] 2018-11-26 19:55
bump

**Comment by mattpatera-ych** [comment] 2019-11-07 23:45
Bump

**Comment by frankdejonge** [comment] 2020-08-09 19:25
Hi, I'm not able to reproduce this. I use this script and that works fine:

```php
<?php

use League\Flysystem\AzureBlobStorage\AzureBlobStorageAdapter;
use League\Flysystem\Filesystem;
use MicrosoftAzure\Storage\Blob\BlobRestProxy;

include __DIR__.'/vendor/autoload.php';

$zip = new ZipArchive();
var_dump($zip->open(__DIR__ . '/some.zip', ZipArchive::OVERWRITE | ZipArchive::CREATE));
$zip->addFromString('filename.txt', 'contents');
$zip->addEmptyDir('dirname');
$zip->addFromString('dirname/filename.txt', 'contents');
$zip->close();
unset($zip);

$client = BlobRestProxy::createBlobService('your connection string');
$adapter = new AzureBlobStorageAdapter($client, 'container-name');
$filesystem = new Filesystem($adapter);
$filesystem->writeStream('some.zip', fopen(__DIR__.'/some.zip', 'r+'));
var_dump($filesystem->listContents());
```

Since this issue is so old, I'll close it, but feel free to re-open one with a script to reproduce it.

**Closed by frankdejonge** 2020-08-09 19:25 UTC
